### ISSUE TITLE
Rin dosen't spawn

### ISSUE THREAD

**Issue by Zemogiter** [misterslime/RinSatsukiMod#1]
The mod-browser description states this NPC is unlocked by defeating EoC. I'm already in hardmode and she does not show up. And yes I do have an empty room. 
[client.log](https://github.com/misterslime/RinSatsukiMod/files/4704714/client.log)
![Census](https://user-images.githubusercontent.com/24385408/83311854-cc5c5100-a210-11ea-883a-fb5c628e5c4c.png)

**Comment by misterslime** [comment]
Where does it say that she appears after the EoC is defeated? She appears after you've defeated at least 1 mech boss and it's day time. Have you defeated one yet?

Also Census support is coming in the next update.

**Comment by Renari** [comment]
> Also Census support is coming in the next update.

Thanks, look forward to this.
