### ISSUE TITLE
Infinite Scaling

### ISSUE THREAD

**Issue by JustSomeDog** [misterslime/RinSatsukiMod#2]
I like the idea of accessories becoming stronger and adding more stats as you reroll them, but the infinite scaling on life regen can make you almost immortal. I used the Stat Meter item from the Calamity mod to view the life regen that the reforges provide and found that the stat was constantly rising, making you only killable from being one-shot or while debuffed. I'm not sure if the multiple stats on an accessory is intentional, but I feel its a really cool idea. The not dying thing takes a bit of the fun out of it though. Here's some screenshots of the stats before and after equipping.

Stats of accessory:
![20200629141047_1](https://user-images.githubusercontent.com/67602307/86042252-e1492180-ba14-11ea-8ca8-b7153c48d5a3.jpg)

Stats before equipping:
![20200629141100_1_LI](https://user-images.githubusercontent.com/67602307/86042327-fd4cc300-ba14-11ea-820a-14dbb27f90c6.jpg)

Stats after equipping:
![20200629141100_1_LI_Moment (2)](https://user-images.githubusercontent.com/67602307/86042383-148bb080-ba15-11ea-97f1-70e9edb17404.jpg)

**Comment by misterslime** [comment]
That should not be happening. It will be fixed in the next update.

Edit: nvm they will be fixed in the next next update.
